networks:
  reverse-proxy:
    external: true
  dolibarr:
    name: "dolibarr"
    driver: "bridge"

services:
  database:
    image: "postgres:alpine"
    restart: "no"
    env_file: ".env"
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DATABASE}"
    networks:
      - "dolibarr"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"

  dolibarr:
    image: "dolibarr/dolibarr:latest"
    restart: "no"
    depends_on:
      - "database"
    env_file: ".env"
    environment:
      DOLI_DB_HOST: "database"
      DOLI_DB_USER: "${DATABASE_USERNAME}"
      DOLI_DB_PASSWORD: "${DATABASE_PASSWORD}"
      DOLI_DB_NAME: "${DATABASE_DATABASE}"
    networks:
      - "reverse-proxy"
      - "dolibarr"
    volumes:
      - "./dolibarr/custom:/var/www/custom"
      - "./dolibarr/documents:/var/www/documents"
