networks:
  reverse-proxy:
    external: true
  ollama-openwebui:
    name: "ollama-openwebui"
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "172.16.1.0/24"
          ip_range: "172.16.1.0/24"
          gateway: "172.16.1.1"

services:
  ollama:
    container_name: "ollama"
    image: "ollama/ollama:latest"
    restart: "no"
    networks:
      - "ollama-openwebui"
    volumes:
      - "./ollama/data:/root/.ollama"

  openwebui:
    container_name: "openwebui"
    image: "ghcr.io/open-webui/open-webui:main"
    restart: "no"
    depends_on:
      - "ollama"
    networks:
      - "reverse-proxy"
      - "ollama-openwebui"
    volumes:
      - "./openwebui/data:/app/backend/data"
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
