networks:
  reverse-proxy:
    name: "reverse-proxy"
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "172.16.0.0/24"
          ip_range: "172.16.0.0/24"
          gateway: "172.16.0.1"

services:
  reverse-proxy:
    container_name: "reverse-proxy"
    image: "caddy:2-alpine"
    restart: "unless-stopped"
    env_file: ".env"
    cap_add:
      - "NET_ADMIN"
    networks:
      - "reverse-proxy"
    ports:
      - "127.0.0.1:2019:2019/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./caddy/config:/config"
      - "./caddy/data:/data"
      - "./caddy/default_site:/usr/share/caddy:ro"
